### PR TITLE
Fix miss-use assertion_id in assertion

### LINKED ISSUE #148: missuse assertion_id in assertion
Hi All

https://github.com/DMTF/SPDM-Responder-Validator/blob/c61591de2d692de64bdcd1ddcee7880a35ac93fc/common_test_framework/library/common_test_utility_lib/common_test_utility_lib.c#L250-L259

https://github.com/DMTF/SPDM-Responder-Validator/blob/c61591de2d692de64bdcd1ddcee7880a35ac93fc/library/spdm_responder_conformance_test_lib/spdm_responder_test_1_version.c#L42-L48

`common_test_record_test_assertion()`'s third parameter is `assertion_id`.
The `assertion_id` of the first assertion in all TCs is set to `COMMON_TEST_ID_END`.
Although the `COMMON_TEST_ID_END` value is 0x00, it is not a problem, but it would be better to change it to `0` for readability.

### PR DESCRIPTION
**Pull request by hiption**
fix #148

### CODE REVIEW

**Review by steven-bellock — DISMISSED** [review]

File: library/spdm_responder_conformance_test_lib/spdm_responder_test_12_heartbeat_ack.c [hunk 1]
```diff
@@ -409,15 +409,15 @@ void spdm_test_case_heartbeat_ack_unexpected_request (void *test_context)
...
+            0,
             COMMON_TEST_RESULT_NOT_TESTED, "key_exchange failure");
         return;
     }
     if (test_buffer->heartbeat_period == 0) {
         common_test_record_test_assertion (
             SPDM_RESPONDER_TEST_GROUP_MEASUREMENTS,
             SPDM_RESPONDER_TEST_CASE_MEASUREMENTS_UNEXPECTED_REQUEST_IN_DHE_SESSION_HS,
-            COMMON_TEST_ID_END,
+            1,
```
Comment (jyao1) [inline library/spdm_responder_conformance_test_lib/spdm_responder_test_12_heartbeat_ack.c:420]: this should be 0, because the test is not started.

File: library/spdm_responder_conformance_test_lib/spdm_responder_test_12_heartbeat_ack.c [hunk 2]
```diff
@@ -450,7 +450,7 @@ void spdm_test_case_heartbeat_ack_unexpected_request (void *test_context)
     }
     common_test_record_test_assertion (
         SPDM_RESPONDER_TEST_GROUP_HEARTBEAT_ACK,
-        SPDM_RESPONDER_TEST_CASE_HEARTBEAT_ACK_UNEXPECTED_REQUEST_IN_DHE_SESSION_HS, 1,
+        SPDM_RESPONDER_TEST_CASE_HEARTBEAT_ACK_UNEXPECTED_REQUEST_IN_DHE_SESSION_HS, 3,
```
Comment (jyao1) [inline library/spdm_responder_conformance_test_lib/spdm_responder_test_12_heartbeat_ack.c:453]: This value 1 is correct, according to https://github.com/DMTF/SPDM-Responder-Validator/blob/main/doc/12.HeartbeatAck.md

**Comment by jyao1** [comment]
@hiption , I feel there might be some misunderstanding.

I define the test ID to be environment or assertion. See the step in "TestSetup" or "Assertion" in each test doc, such as https://github.com/DMTF/SPDM-Responder-Validator/blob/main/doc/12.HeartbeatAck.md.

Every unique value is assigned to ASSERTION in the doc. Please don't change it. Otherwise it will cause document mismatch.

For environment setting error, there is no value to assign different ID, because the ID will NOT be counted in the final result.
It is just environment setting failure, and tests are skipped.

File: library/spdm_responder_conformance_test_lib/spdm_responder_test_12_heartbeat_ack.c [hunk 3]
```diff
@@ -409,15 +409,15 @@ void spdm_test_case_heartbeat_ack_unexpected_request (void *test_context)
         common_test_record_test_assertion (
             SPDM_RESPONDER_TEST_GROUP_MEASUREMENTS,
```
Comment (hiption) [inline library/spdm_responder_conformance_test_lib/spdm_responder_test_12_heartbeat_ack.c:410]: Is `SPDM_RESPONDER_TEST_GROUP_MEASUREMENTS` correct?
I think `SPDM_RESPONDER_TEST_GROUP_HEARTBEAT_ACK` is correct.

**Comment by hiption** [comment]
Hi @jyao1 
I will check the test doc.
BTW, it seems that there are some codes I mentioned above where group_id and test_id are incorrectly used.

**Comment by jyao1** [comment]
> Hi @jyao1 I will check the test doc. BTW, it seems that there are some codes I mentioned above where group_id and test_id are incorrectly used.

Sure. If you notice any code/doc mismatch, please submit issue and patch directly. We should get them fixed (in either code or doc)

**Comment by hiption** [comment]
ok

File: library/spdm_responder_conformance_test_lib/spdm_responder_test_12_heartbeat_ack.c (hunk 3 above)
Comment (jyao1) [reply library/spdm_responder_conformance_test_lib/spdm_responder_test_12_heartbeat_ack.c:410]: You are right. This is a bug.

**Comment by hiption** [comment]
Hi all

I have updated this PR.

this commit includes :
change 'COMMON_TEST_ID_END' to 0
sync TC and Doc
